### ISSUE TITLE
Using Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [ClemRz/Solar-Water-Heater-Monitor#1]
When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received bytes are waiting in a buffer in the Wire library. Once the Wire.requestFrom() returns, the code runs fast without delay and waiting and retrieving data from that buffer with Wire.read() is fast.

In your file "Solar-Water-Heater-Monitor/software design/esp8266/i2c.ino" there is no need for the yield() between retrieving data from that buffer. That yield() in that location has the same meaning as any yield() anywhere in the code. 

There is also no need to read unwanted bytes from that buffer.

It is not really a "bug" and it is not "wrong", but looking at the code it seems a little odd.

**Comment by ClemRz** [comment]
Hi Koepel,

Thank you so much for your spontaneous feedback! I've updated the code as you mentioned.

One question: how did you detected that oddness? :)

Thanks again!

**Comment by Koepel** [comment]
I found your code by a search. Others use the Wire library in the wrong way and I try to reduce that.

**Comment by ClemRz** [comment]
Oh, wow. It has been indexed very quickly then!

I've been doing some research on the Internet about using the ESP8266 as a I2C slave and I couldn't find any working example so far, some people say this is not currently possible. Do you know about ESP8266? Any thoughts?

Thanks.

**Comment by Koepel** [comment]
The AVR ATmega chips have a hardware I2C controller, and that can already be a problem since a part is in software with the onReceive and the onRequest functions.
If I understand it correctly, the ESP8266 appears to have hardware for I2C, but it does not. Therefore the Wire/TWI library uses a software I2C. A software I2C is only for master mode, since a software slave mode is (almost) impossible.

Perhaps the ESP32 will get a library for hardware I2C for master and slave. I don't know if that is available yet, but at least some are talking about it.

**Comment by ClemRz** [comment]
Thanks for clarifying that! 👍
